config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :edit, :update]

  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
      
    # 十大人氣餐廳
      get :ranking
    end

    member do
      # 瀏覽個別餐廳的 Dashboard
      # GET restaurants/:id/dashboard
      get :dashboard

      # 收藏 / 取消收藏
      post :favorite
      post :unfavorite

      # 按讚 / 收回讚
      post :like
      post :unlike
    
    end

  end

  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  
  belongs_to :category
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end


end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "餐廳資訊建立成功"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "建立餐廳資訊失敗"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "餐廳資訊更新成功"
      redirect_to admin_restaurant_path(@restaurant)
    else
      flash.now[:alert] = "更新失敗"
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "資料已刪除"
  end



  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all 
  end

  def show
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  def favorite
    @restaurant = Restaurant.find(params[:id])
    Favorite.create(restaurant: @restaurant, user: current_user)
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    Like.create(restaurant: @restaurant, user: current_user)
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end

  def unlike
    @restaurant = Restaurant.find(params[:id])
    like = Like.where(restaurant: @restaurant, user: current_user).first
    like.destroy
    redirect_back(fallback_location: root_path)
  end

  def ranking
    @restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end



  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<div class="container">
  <div class="row">

    <% if @restaurant.errors.any? %>
      <h4>Oops!!資訊輸入錯誤!!</h4>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
    <% end %>

    <%= form_with(model: [:admin, @restaurant]) do |f| %>

      <div class="form-group <%= (f.object.errors[:name].any?)? "has-error" : "" %>">
        <%= f.label :name, "餐廳名稱" %>
        <%= f.text_field :name, class: "form-control" %>

        <% if f.object.errors[:name] %>
        <span class="help-block"><%= safe_join(f.object.errors[:name], "、") %></span>
        <% end %>
      </div>

      <div class="form-group" > 
        <%= f.label :category_id, "餐廳分類" %>
        <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"} %>
      </div>

      <div class="form-group" > 
        <%= f.label :tel, "聯繫電話" %>
        <%= f.text_field :tel, class: "form-control" %>
      </div> 

      <div>
        <%= f.label :address, "餐廳地址" %>
        <%= f.text_field :address, class: "form-control" %>
      </div>

      <div class="form-group" > 
        <%= f.label :opening_hours, "營業時間" %>
        <%= f.text_field :opening_hours, class: "form-control" %>
      </div>

      <div class="form-group" > 
        <%= f.label :description, "餐廳簡介" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group" > 
        <%= f.label :image, "餐廳照片" %>
        <%= image_tag @restaurant.image.url, width: '300px' if @restaurant.image? %>
        <%= f.file_field :image %>
      </div>

       <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>

<br>
<%= link_to "回上層", url_for(request.env["HTTP_REFERER"] || root_path) %>

  </div>
</div>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<div class="container">

  <h1>--餐廳後台--</h1>
  <div>
    <%= link_to '餐廳總覽', admin_restaurants_path %> |
    <%= link_to '分類總覽', admin_categories_path %>
  </div>
  
  <div class="row">

    <div class="col-md-12">

      <div>
        <%= link_to '新建餐廳資訊', new_admin_restaurant_path, class: "btn btn-primary" %>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>編號</th>
            <th>餐廳分類</th>
            <th>餐廳名稱</th>
            <th>編輯</th>
            <th>刪除</th>
          </tr>
        </thead>
        <tbody>
          <% @restaurants.each do |restaurant| %>
          <tr>
            <th width="5%" scope="row"><%= restaurant.id %></th>
            <td width="15%">[<%= restaurant.category.name %>]</td>
            <td><%= link_to admin_restaurant_path(restaurant) do %>  <%# show改的,直接點選餐廳名稱後連結到餐廳頁面%>
              <%= restaurant.name %>
            <% end %>
            </td>
            <td width="10%">
              <%= button_to 'Edit', edit_admin_restaurant_path(restaurant), class: "btn btn-primary", method: :get %>
            </td>
            <td width="10%">
              <%= button_to "Delete", admin_restaurant_path(restaurant), class: "btn btn-danger", method: :delete, onclick: "return confirmDestroy('確定要刪除此筆餐廳資訊嗎？')" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="text-center">
        <%= paginate @restaurants %>
      </div>

    </div>

  </div>
</div>

app/views/admin/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <h2>Oops!!資訊輸入錯誤!!</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: [:admin, @restaurant]) do |f| %>

<div class="form-group <%= (f.object.errors[:name].any?)? "has-error" : "" %>">
  <%= f.label :name, "餐廳名稱" %>
  <%= f.text_field :name %>

  <% if f.object.errors[:name] %>
  <span class="help-block"><%= safe_join(f.object.errors[:name], "、") %></span>
  <% end %>
</div>
<div class="form-group" > 
  <%= f.label :tel, "聯繫電話" %>
  <%= f.text_field :tel %>
</div>
<div>
  <%= f.label :address, "餐廳地址" %>
  <%= f.text_field :address %>
</div>
<div class="form-group" > 
  <%= f.label :opening_hours, "營業時間" %>
  <%= f.text_field :opening_hours %>
</div>
<div class="form-group" > 
  <%= f.label :description, "餐廳簡介" %>
  <%= f.text_area :description %>
</div>
  <%= f.submit "新增資訊"%>
<% end %>
<br>
<%= link_to '回餐廳目錄', admin_restaurants_path %>

app/views/admin/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
    </div>

    <div class="col-md-4">
      <%= image_tag @restaurant.image.url, width: '600px', class: "img-responsive center-block" if @restaurant.image? %>
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>餐廳分類:</strong> <%= @restaurant.category.name %></li>
          <li><strong>營業時間:</strong> <%= @restaurant.opening_hours %></li>
          <li><strong>聯絡電話:</strong> <%= @restaurant.tel %></li>
          <li><strong>餐廳地址:</strong> <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
    </div>
    <div class="clearfix">
    
    </div>
  </div>
</div>
<div>
  <hr>
  <%= link_to "回上層", url_for(request.env["HTTP_REFERER"] || root_path) %>
  <hr>
</div>