config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :edit, :update]

  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
      
    # 十大人氣餐廳
      get :ranking
    end

    member do
      # 瀏覽個別餐廳的 Dashboard
      # GET restaurants/:id/dashboard
      get :dashboard

      # 收藏 / 取消收藏
      post :favorite
      post :unfavorite

      # 按讚 / 收回讚
      post :like
      post :unlike
    
    end

  end

  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :restaurants, dependent: :restrict_with_error
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:update, :destroy]

  def index
  @categories = Category.all
  # 這裡是new or edit 的form所需要的值，如果有url有id就將form帶入edit，沒有就new。
    if params[:id]
      set_category
    else
      @category = Category.new
    end
  end

  def create
  @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "新餐廳分類已建立"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end

def update
  if @category.update(category_params)
    redirect_to admin_categories_path
    flash[:notice] = "餐廳分類名稱修改成功"
  else
    @categories = Category.all
    render :index
  end
end


def destroy
  @category.destroy
  flash[:alert] = "餐廳分類刪除成功"
  redirect_to admin_categories_path
end

private

def category_params
  params.require(:category).permit(:name)
end

def set_category
  @category = Category.find(params[:id])
end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

def show
  @categories = Category.all
  @category = Category.find(params[:id])
  @restaurants = @category.restaurants.page(params[:page]).per(9)
end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">

  <h1>餐廳分類總表</h1>
  <div>
    <%= link_to '餐廳總覽', admin_restaurants_path %> |
    <%= link_to '分類總覽', admin_categories_path %>
  </div>
<br>
  <div class="form-inline" >
  <%= form_for [:admin, @category] do |f| %>
    <div class="form-group">
      <%= f.text_field :name, placeholder: "Category Name",  class: "form-control" %>
    </div>
      <% if params[:id] %>
        <%= f.submit "變更分類名稱", class: "btn btn-primary" %>
      <% else %>
        <%= f.submit "新增分類", class: "btn btn-primary" %>
      <% end %>
  <% end %>
  <% if @category.errors.any? %>
    Categotry <%= @category.errors.full_messages.to_sentence %>
  <% end %>
</div>
<br>
  <div class="row">

    <div class="col-md-4">

      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>分類名稱</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <th width="5%" scope="row"><%= category.id %></th>

            <td width="40%"><%= category.name %>&nbsp;&nbsp;              
            <%= link_to admin_categories_path(id: category.id) do %>
              <span class="glyphicon glyphicon-pencil" aria-hidden="true">
            <% end %>
            <div style="float:right;">
            <%= button_to admin_category_path(category), method: :delete, onclick: "return confirmDestroy('確定要刪除此分類嗎？')" do %>
              <span class="glyphicon glyphicon-trash" aria-hidden="true">
            <% end %>
            </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>