config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :edit, :update]

  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
      
    # 十大人氣餐廳
      get :ranking
    end

    member do
      # 瀏覽個別餐廳的 Dashboard
      # GET restaurants/:id/dashboard
      get :dashboard

      # 收藏 / 取消收藏
      post :favorite
      post :unfavorite

      # 按讚 / 收回讚
      post :like
      post :unlike
    
    end

  end

  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :restaurant

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :restaurant, counter_cache: true
  # counter_cache 可以自動回傳 size 方法結果，計算關聯物件的數量
  # 必須在關聯 Model 上加一個欄位，慣例命名為 {table_name}_count
  # 指南：https://rails.ruby.tw/association_basics.html
  # 打開 counter_cache 之後，也會啟動這些相關方法：http://api.rubyonrails.org/v5.0/classes/ActiveRecord/CounterCache/ClassMethods.html
  # 有了 counter_cache 之後，就不需要手工撰寫的方法了，可以回 Model 和 Controler 將之刪除
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  
  belongs_to :category
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates_presence_of :name
  mount_uploader :avatar, AvatarUploader
         
  # 「使用者評論很多餐廳」的多對多關聯
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  # 「使用者收藏很多餐廳」的多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant


  # 「使用者按讚很多餐廳」的多對多關聯
  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant
  
  def admin?
    self.role == "admin"
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  # 這個 Controller 繼承 ApplicationController 所以可以用自己與 Application 的 method
  # 這裡的 namespace controller 在全部繼承這個Base controller 就可以使用這裡的 method了！
  before_action :authenticate_admin

  private

   def authenticate_admin
     unless current_user.admin?
       flash[:alert] = "Not allow!"
       redirect_to root_path
     end
   end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  # Devise 客製化屬性的使用說明：  https://github.com/plataformatec/devise#strong-parameters

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

def show
  @categories = Category.all
  @category = Category.find(params[:id])
  @restaurants = @category.restaurants.page(params[:page]).per(9)
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all 
  end

  def show
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  def favorite
    @restaurant = Restaurant.find(params[:id])
    Favorite.create(restaurant: @restaurant, user: current_user)
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    Like.create(restaurant: @restaurant, user: current_user)
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end

  def unlike
    @restaurant = Restaurant.find(params[:id])
    like = Like.where(restaurant: @restaurant, user: current_user).first
    like.destroy
    redirect_back(fallback_location: root_path)
  end

  def ranking
    @restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end



  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update]
  
  def show
    @commented_restaurants = @user.restaurants.uniq
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <!-- 刪除跳出確認視窗-->
    <%= javascript_importmap_tags %>
    <script>
      function confirmDestroy(message) {
      if (!confirm(message)) {
      return false;
       }
      }
    </script> 


  </head>

  <body>

       <!-- 導覽列 -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Wally's餐廳評論網", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="pull-right text-right nav navbar-nav">
            <% if current_user %>
              <% if current_user.admin? %>
                <li><%= link_to 'Admin後台', admin_restaurants_path %></li>
              <% end %>
            <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
            <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
            <% else %>
            <li><%= link_to('註冊', new_user_registration_path) %></li>
            <li><%= link_to('登入', new_user_session_path) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% if flash[:notice] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      </div>
    </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      </div>
    </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_favorite.html.erb
<% if restaurant.is_favorited?(current_user) %>
  <%= button_to unfavorite_restaurant_path(restaurant), class: "btn btn-default", method: :post do %>
    <span class="glyphicon glyphicon-star-empty" aria-hidden="true">取消收藏</span>
  <% end %>
<% else %>
  <%= button_to favorite_restaurant_path(restaurant), class: "btn btn-default", method: :post do %>
    <span class="glyphicon glyphicon-star" aria-hidden="true">收藏</span>
  <% end %>
<% end %>

<% if restaurant.is_liked?(current_user) %>
  <span class="glyphicon glyphicon-heart" aria-hidden="true"> Already Liked</span>
  <%= button_to unlike_restaurant_path(restaurant), class: "btn btn-info", method: :post do %>
  <span class="glyphicon glyphicon-remove" aria-hidden="true"> Unlike</span>
  <% end %>
<% else %>
  <%= button_to like_restaurant_path(restaurant), class: "btn btn-info", method: :post do %>
  <span class="glyphicon glyphicon-heart" aria-hidden="true"> Like</span>
  <% end %>
<% end %>

app/views/shared/_restaurant_list.html.erb
<!-- restaurants list，有多寫restaurant-item的class style -->
    <% @restaurants.each do |restaurant| %>
      <div class="col-sm-6 col-md-4">
        <div class="restaurant-item">
          <%= link_to restaurant_path(restaurant) do %>
           <%= image_tag restaurant.image.url, class: "img-responsive center-block"  if restaurant.image? %>            
           <%= image_tag "https://via.placeholder.com/200", class: "img-responsive center-block img-rounded"  unless restaurant.image?%>      
          <% end %>      
          <div class="caption">
            <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
            <p class="label label-default"><%= restaurant.category.name %><p>
            <p><%= truncate(restaurant.description, length: 80) %></p>
            <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
          </div>
        </div>
      </div>

    <% end %>
      
    <!-- 有generate kaminari paginate bootstrap style -->
    <div class="text-center">
      <%= paginate @restaurants %>
    </div>